### ISSUE TITLE
second

### ISSUE THREAD

**Issue by justnik98** [dixtar321/labs#1]
frist -> second
https://github.com/dixtar321/labs/blob/a23c2e046f11294164b77aa54502540e09b9a40f/%D0%9B%D0%B0%D0%B1%D0%B0%20000/%D0%9B%D0%B0%D0%B1%D0%BE%D1%80%D0%B0%D1%82%D0%BE%D1%80%D0%BD%D0%B0%D1%8F%20%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0%20%E2%84%960.cpp#L7

**Comment by dixtar321** [comment]
> frist -> second
> https://github.com/dixtar321/labs/blob/a23c2e046f11294164b77aa54502540e09b9a40f/%D0%9B%D0%B0%D0%B1%D0%B0%20000/%D0%9B%D0%B0%D0%B1%D0%BE%D1%80%D0%B0%D1%82%D0%BE%D1%80%D0%BD%D0%B0%D1%8F%20%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0%20%E2%84%960.cpp#L7

You god damn right
